admissionController:
  initContainer:
    image:
      registry: 452336408843.dkr.ecr.us-west-2.amazonaws.com
      repository: kyvernopre
      tag: latest
  container:
    image:
      registry: 452336408843.dkr.ecr.us-west-2.amazonaws.com
      repository: kyverno
      tag: latest

backgroundController:
  image:
    registry: 452336408843.dkr.ecr.us-west-2.amazonaws.com
    repository: kyverno-background-controller
    tag: latest

cleanupController:
  image:
    registry: 452336408843.dkr.ecr.us-west-2.amazonaws.com
    repository: kyverno-cleanup-controller
    tag: latest

reportsController:
  image:
    registry: 452336408843.dkr.ecr.us-west-2.amazonaws.com
    repository: kyverno-reports-controller
    tag: latest

#helm upgrade --install kyverno kyverno/kyverno \
#  -n kyverno --create-namespace \
#  --set installCRDs=true \
#  --set webhooks.enabled=true \
#  --set webhooks.autoGenerateCert=true \
#  --set webhooks.useCertManager=false \
#  --set-string 'config.webhookAnnotations.admissions\.enforcer/disabled'="false" \
#  --set-string features.generateValidatingAdmissionPolicy.enabled="false" \
#  --set-string features.generateMutatingAdmissionPolicy.enabled="false"


